### ISSUE TITLE
TypeError: Cannot read property 'xsd:complexType' of undefined

### ISSUE THREAD

**Issue by johnmiroki** [ui5experts/ui5-schemas#100]
Could you please help with the following errors? Thanks! 

✗ npx ui5-schemas
npx: installed 116 in 16.837s
ui5-schemas info Attempting to download latest version of 'sapui5'. Determining latest version...
ui5-schemas info https://sapui5.hana.ondemand.com/resources/sap-ui-version.json
ui5-schemas info Detected version of sdk 'sapui5' is '1.87.0'
ui5-schemas info Preparing 'sapui5' schemas in version '1.87.0'...
ui5-schemas info Yay, all schema files were successfully downloaded!
ui5-schemas info [enhance] Making schemas even cooler...
ui5-schemas error [enhance] TypeError: Cannot read property 'xsd:complexType' of undefined
    at sapUiCoreView (/Users/i/.npm/_npx/94835/lib/node_modules/ui5-schemas/lib/upgrade.js:29:34)
    at /Users/i/.npm/_npx/94835/lib/node_modules/ui5-schemas/lib/upgrade.js:108:9
    at Parser.<anonymous> (/Users/i/.npm/_npx/94835/lib/node_modules/ui5-schemas/node_modules/xml2js/lib/parser.js:303:18)
    at Parser.emit (events.js:314:20)
    at SAXParser.onclosetag (/Users/i/.npm/_npx/94835/lib/node_modules/ui5-schemas/node_modules/xml2js/lib/parser.js:261:26)
    at emit (/Users/i/.npm/_npx/94835/lib/node_modules/ui5-schemas/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/Users/i/.npm/_npx/94835/lib/node_modules/ui5-schemas/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/Users/i/.npm/_npx/94835/lib/node_modules/ui5-schemas/node_modules/sax/lib/sax.js:889:7)
    at SAXParser.write (/Users/i/.npm/_npx/94835/lib/node_modules/ui5-schemas/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/Users/i/.npm/_npx/94835/lib/node_modules/ui5-schemas/node_modules/xml2js/lib/parser.js:322:31)
    at Parser.parseString (/Users/i/.npm/_npx/94835/lib/node_modules/ui5-schemas/node_modules/xml2js/lib/parser.js:5:59)
    at /Users/i/.npm/_npx/94835/lib/node_modules/ui5-schemas/lib/upgrade.js:103:14

**Comment by pedromagueija** [comment]
I'm experiencing the same issue for SAPUI5 1.90.0.
