### ISSUE TITLE
Issue when running ui5-schemas - enhance

### ISSUE THREAD

**Issue by sfkc** [ui5experts/ui5-schemas#17]
Hey there, have the following issue and not sure if bug in code or something I did. Can you help?
Removed user details.

`C:\Users\-\ui5schemas>ui5-schemas

ui5-schemas info Preparing 'sapui5' schemas in version 'latest'...

ui5-schemas info Yay, all schema files were successfully downloaded!

ui5-schemas info [enhance] Making schemas even cooler...

ui5-schemas error [enhance] TypeError: Cannot read property 'xsd:complexType' of undefined

    at sapUiCoreView (C:\Users\-\AppData\Roaming\npm\node_modules\ui5-schemas\lib\upgrade.js:27:34)

    at parser.parseString (C:\Users\-\AppData\Roaming\npm\node_modules\ui5-schemas\lib\upgrade.js:72:9)

    at Parser.<anonymous> (C:\Users\-\AppData\Roaming\npm\node_modules\ui5-schemas\node_modules\xml2js\lib\parser.js:303:18)

    at Parser.emit (events.js:189:13)

    at SAXParser.onclosetag (C:\Users\-\AppData\Roaming\npm\node_modules\ui5-schemas\node_modules\xml2js\lib\parser.js:261:26)

    at emit (C:\Users\-\AppData\Roaming\npm\node_modules\ui5-schemas\node_modules\sax\lib\sax.js:624:35)

    at emitNode (C:\Users\-\AppData\Roaming\npm\node_modules\ui5-schemas\node_modules\sax\lib\sax.js:629:5)

    at closeTag (C:\Users\-\AppData\Roaming\npm\node_modules\ui5-schemas\node_modules\sax\lib\sax.js:889:7)

    at SAXParser.write (C:\Users\-\AppData\Roaming\npm\node_modules\ui5-schemas\node_modules\sax\lib\sax.js:1436:13)

    at Parser.exports.Parser.Parser.parseString (C:\Users\-\AppData\Roaming\npm\node_modules\ui5-schemas\node_modules\xml2js\lib\parser.js:322:31)`

Thanks!

**Comment by Raptor05** [comment]
Same problem here

**Comment by Rob077** [comment]
Same issue when using most recent version of ui5-schemas and try to link it with WebStorm 2019.1

_ui5-schemas --link_

**Comment by MaximilienFourmyBeyond** [comment]
This could be solved by providing the version like this:
ui5-schemas --version 1.64.0

For SDK sapui5, so you can find the versions available here:
https://tools.hana.ondemand.com/#sapui5

For openui5, you can find the versions available here:
https://openui5.org/releases/

The issue for sapui5 happens because the schemas url needs the version number :
Plugin try this and it give an error 404:
https://sapui5.hana.ondemand.com/downloads/schemas/sap.ui.demokit.xsd
But with the version number, it's ok :
https://sapui5.hana.ondemand.com/1.64.1/downloads/schemas/sap.ui.core.xsd

With sdk openui5, it's ok, the schemas are downloadable without providing the version in the url.
