### ISSUE TITLE
XSD not loading for UI5 1.85.2

### ISSUE THREAD

**Issue by ddokuchaev** [ui5experts/ui5-schemas#96]
When I try to use the library for Webstorm I have this log:
C:\Projects\Webstorm\SAPUI5 Apps>ui5-schemas
ui5-schemas info Attempting to download latest version of 'sapui5'. Determining latest version...
ui5-schemas info https://sapui5.hana.ondemand.com/resources/sap-ui-version.json
ui5-schemas info Detected version of sdk 'sapui5' is '1.85.3'
ui5-schemas info Preparing 'sapui5' schemas in version '1.85.3'...
ui5-schemas info Yay, all schema files were successfully downloaded!
ui5-schemas info [enhance] Making schemas even cooler...
ui5-schemas info [link] Discovered an .idea project! Registering schemas...
ui5-schemas error [enhance] TypeError: Cannot read property 'xsd:complexType' of undefined
    at sapUiCoreView (C:\Projects\Webstorm\SAPUI5 Apps\node_modules\ui5-schemas\lib\upgrade.js:29:34)
    at C:\Projects\Webstorm\SAPUI5 Apps\node_modules\ui5-schemas\lib\upgrade.js:107:9
    at Parser.<anonymous> (C:\Projects\Webstorm\SAPUI5 Apps\node_modules\xml2js\lib\parser.js:303:18)
    at Parser.emit (node:events:329:20)
    at SAXParser.onclosetag (C:\Projects\Webstorm\SAPUI5 Apps\node_modules\xml2js\lib\parser.js:261:26)
    at emit (C:\Projects\Webstorm\SAPUI5 Apps\node_modules\sax\lib\sax.js:624:35)
    at emitNode (C:\Projects\Webstorm\SAPUI5 Apps\node_modules\sax\lib\sax.js:629:5)
    at closeTag (C:\Projects\Webstorm\SAPUI5 Apps\node_modules\sax\lib\sax.js:889:7)
    at SAXParser.write (C:\Projects\Webstorm\SAPUI5 Apps\node_modules\sax\lib\sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (C:\Projects\Webstorm\SAPUI5 Apps\node_modules\xml2js\lib\parser.js:322:31)
    at Parser.parseString (C:\Projects\Webstorm\SAPUI5 Apps\node_modules\xml2js\lib\parser.js:5:59)
    at C:\Projects\Webstorm\SAPUI5 Apps\node_modules\ui5-schemas\lib\upgrade.js:102:14
ui5-schemas info [link] Schemas successfully registered!

The issue in XSD files - they are empty:
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1></body></html>

Node JS - v15.2.0.
SAP UI5 - 1.85.2

**Comment by ddokuchaev** [comment]
Sorry, I`m to read the readme very late :)
Close the issue ;)
